export const ENGINEERING_REVIEW_PHASES = [
  { id: 'syntax-ast', title: 'Syntax and AST analysis', rule: 'syntax' },
  { id: 'template', title: 'Angular template analysis', rule: 'template' },
  { id: 'runtime', title: 'Runtime validation', rule: 'runtime' },
  { id: 'performance', title: 'Performance analysis', rule: 'performance' },
  { id: 'async-flow', title: 'Async flow analysis', rule: 'async' },
  { id: 'architecture', title: 'Architecture analysis', rule: 'architecture' },
  { id: 'maintainability', title: 'Maintainability analysis', rule: 'maintainability' },
  { id: 'security', title: 'Security analysis', rule: 'security' },
  { id: 'scalability', title: 'Scalability analysis', rule: 'scalability' },
  { id: 'dedup', title: 'Deduplicate findings', rule: 'dedup' },
  { id: 'comments', title: 'Generate final comments', rule: 'comments' },
] as const;

export const MANDATORY_ISSUE_CATEGORIES = [
  'Null/undefined issues',
  'Missing optional chaining',
  'Runtime crash possibilities',
  'Missing error handling',
  'API failure handling',
  'Promise handling problems',
  'Async/await misuse',
  'RxJS issues',
  'Subscription leaks',
  'Race conditions',
  'Repeated API calls',
  'Duplicate requests',
  'Infinite loops',
  'Expensive loops',
  'Heavy template expressions',
  'Change detection problems',
  'Unnecessary rerenders',
  'Signal misuse',
  'Incorrect state updates',
  'Store synchronization issues',
  'Large component complexity',
  'Duplicate logic',
  'Dead code',
  'Unused imports',
  'Incorrect typing',
  'Any type overuse',
  'Wrong Angular lifecycle usage',
  'Event listener leaks',
  'DOM performance problems',
  'Missing trackBy',
  'OnPush optimization opportunities',
  'Form validation problems',
  'IndexedDB/cache synchronization issues',
  'Security issues',
  'XSS risks',
  'SSR/hydration problems',
  'Incorrect dependency injection',
  'Circular dependencies',
  'Runtime rendering bottlenecks',
  'Memory growth patterns',
  'Bad architecture patterns',
  'Improper service separation',
  'Large method complexity',
  'Blocking synchronous operations',
  'Missing loading states',
  'Bad user experience patterns',
  'Repeated calculations',
  'Runtime state inconsistency',
  'Template rendering inefficiencies',
  'Poor scalability patterns',
] as const;

export const REVIEW_CHECK_LABELS = [
  'Null safety analysis',
  'Runtime crash analysis',
  'Angular rendering analysis',
  'RxJS analysis',
  'Performance analysis',
  'Async/API flow analysis',
  'State and signal analysis',
  'Forms analysis',
  'Architecture analysis',
  'Maintainability analysis',
  'Security analysis',
  'SSR and hydration analysis',
  'Scalability analysis',
] as const;
